# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
#############################
# Multi-stage Dockerfile for building and running the MCP server
#############################

# Build stage
FROM node:lts-alpine AS build
WORKDIR /app

# Copy package files and install dependencies (including dev dependencies for building)
COPY package.json package-lock.json ./
RUN npm install

# Copy source files
COPY . .

# Build the project (transpiling TypeScript to JavaScript)
RUN npm run build

# Production stage
FROM node:lts-alpine
WORKDIR /app

# Copy package files and install production dependencies only
COPY package.json package-lock.json ./
RUN npm install --production

# Copy built files from the build stage
COPY --from=build /app/build ./build

# Set the default command to run the MCP server
CMD [ "node", "build/index.js" ]
