# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Install pnpm globally
RUN npm install -g pnpm

# Set working directory
WORKDIR /app

# Copy necessary files
COPY package.json pnpm-lock.yaml ./
COPY tsconfig.json ./
COPY src ./src

# Install dependencies
RUN pnpm install --frozen-lockfile --ignore-scripts

# Build the project
RUN pnpm run build

# Expose port if needed (none by default for stdio-based)

# Start the MCP server
CMD [ "node", "dist/index.js" ]
